<?php
session_start();
session_destroy();

?>

<!DOCTYPE html>
<html>
<head>
	<title>Home Page</title>
	<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

<link rel="stylesheet" href="css/lightbox.min.css">
<script src="js/lightbox.min.js"></script>
  <script src="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"></script>
  <script src="https://code.jquery.com/jquery-3.1.1.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

 

<!-- ICON NEEDS FONT AWESOME FOR CHEVRON UP ICON -->
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">



<link rel="stylesheet" type="text/css" href="style.css">
<link rel="stylesheet" type="text/css" href="style3.css">
<link rel="stylesheet" type="text/css" href="animate .css">

<style>
	section
	{
		margin-top: 50px;
	}
	h1
	{
		text-align: center;
	}
</style>

</head>
<body>
<a href="javascript:" id="return-to-top"><i class="icon-chevron-up"></i></a>
<script>
$(window).scroll(function() {
    if ($(this).scrollTop() >= 50) {        // If page is scrolled more than 50px
        $('#return-to-top').fadeIn(200);    // Fade in the arrow
    } else {
        $('#return-to-top').fadeOut(200);   // Else fade out the arrow
    }
});
$('#return-to-top').click(function() {      // When arrow is clicked
    $('body,html').animate({
        scrollTop : 0                       // Scroll to top of body
    }, 500);
});
</script>

<div class="home-container"><!--this div includes both navbar and slider -->
<nav class="navbar navbar-default navbar-fixed-top">
<div class="container-fluid header-border" style="padding-left:0;padding-right: 0; ">
<div class="container" style="margin-top: 2em; padding-left:0;padding-right: 0;">
<div class="col-md-3">
	<a href="index.php"><img src="images/logo.png" class="img-responsive" style="width: 200px;"></a>
</div>
<div class="col-md-9" style="padding-left:0;padding-right: 0;">
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" style="background-color: transparent;border: none;">
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
</button>
</div>
	<div class="collapse navbar-collapse">
	<ul class="nav navbar-nav"><!--nav class is for removing the bullets generated by ul and navbar-nav is for making the navbar inline-->
	<li><a href="index.php">Home</a></li>
	<li><a href="mission.php">About Us</a></li>
	<li><a href="gallery.php">Gallery</a></li>
    <li><a href="donate.php">Donate</a></li>
	<li><a href="faq.php">FAQs <br>& Queries</a></li>
	<li><a href="#contact">Contact</a></li>
  <script>
$(document).ready(function(){
  // Add smooth scrolling to all links
  $("a").on('click', function(event) {

    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {
      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 500, function(){
   
        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
});
</script>
	</ul>
  <ul class="nav navbar-nav navbar-right">
    <li><a href="signup.php"><span class="glyphicon glyphicon-user">SignUp</span></a></li>
    <li><a href="login.php"><span class="glyphicon glyphicon-log-in">Login</span></a></li>
  </ul>
	</div>
</div>
</div>
</nav>
<div class="carousel media-carousel" id="media-control" data-ride="carousel"><!-- data-ride is used for animating carousel -->
<div class="carousel-inner">
	<div class="item active"><!--active is to show the image -->
		<img src="images/slide1.jpg" style="width:100%;height:700px;" class="img-responsive animated zoomInLeft">
		<div class="carousel-caption">
			<h2 class="animated bounceInLeft">“We make a living by what we get,we make a life by what we give”</h2>
			<a href="donate.php" class="animated rotateInDownLeft btn btn-primary">Help the needy</a>
		</div>
	</div>
		<div class="item"><!--if we put active here it will come one below the other -->
		<img src="images/slide2.jpg" style="width:100%;height:700px;" class="img-responsive animated zoomInRight">
				<div class="carousel-caption">
			<h2 class="animated bounceInRight">"We rise by lifting others"</h2>
			<a href="mission.php" class="animated rotateInDownLeft btn btn-primary">Who we are</a>
		</div>
	</div>
  <div class="item"><!--if we put active here it will come one below the other -->
    <img src="images/slide3.jpg" style="width:100%;height:700px;" class="img-responsive animated zoomInRight">
        <div class="carousel-caption">
      <h2 class="animated bounceInRight">“Giving opens the way for receiving”</h2>
      <a href="signup.php" class="animated rotateInDownLeft btn btn-primary">Are you a NGO</a>
    </div>
  </div>
  <div class="item"><!--if we put active here it will come one below the other -->
    <img src="images/slide4.jpg" style="width:100%;height:700px;" class="img-responsive animated zoomInRight">
        <div class="carousel-caption">
      <h2 class="animated bounceInRight">“Raise your voice to reach the needy”</h2>
      <a href="donate.php" class="animated rotateInDownLeft btn btn-primary">Donate</a>
    </div>
  </div>
</div>
<a class="left carousel-control" data-slide="prev" href="#media-control"><i class="fa fa-chevron-left"></i></a>
<a class="right carousel-control" data-slide="next" href="#media-control"><i class="fa fa-chevron-right"></i></a>
</div>
</div>


<section class="rishabh ">
<h1 class="wow bounceInLeft" data-wow-duration="1s">Helping Hands</h1>
<div class="row helping-hands ">
<div class="col-md-4" class="help text-center wow fadeOut">
<img src="images/swades.jpg" class="img-responsive center-block wow fadeIn" data-wow-duration="5s"><br><br>
<p class="wow rubberBand" data-wow-duration="3s">Our Mission is to <b>empower 1 million rural Indians every 5-6 years</b>, creating a permanent, irreversible change for good. We believe in a <b>holistic 360-degree development</b> with a focus on four key verticals <b>- Health, Education, Water & Sanitation, and Economic Development.</b> This model empowers our communities with the capability of creating choices for themselves and their families, allowing them to transform their own lives and ensuring a permanent and irreversible change for good. </p></div>
<div class="col-md-4" class="help text-center">
<img src="images/smile.png" class="img-responsive center-block wow fadeIn" data-wow-duration="5s"><br><br>
	<p class="wow rubberBand" data-wow-duration="3s"><b>Smile Foundation</b> believes that unless members of the <b>civil society</b> are involved proactively in the <b>process of development</b>, sustainable change will not happen. Following this model of Civic Driven Change, Smile Foundation sensitizes and engages <b>the civil society, making it an active partner in all its welfare initiatives.</b></p>
</div>
<div class="col-md-4" class="help text-center">
<img src="images/care.png" class="img-responsive center-block wow fadeIn" data-wow-duration="5s"><br><br>
	<p class="wow rubberBand" data-wow-duration="3s">We seek a <b>world of hope</b>, tolerance and social justice, where <b>poverty has been overcome</b> and people live in dignity and security. <b>CARE India</b> helps alleviate poverty and social exclusion by <b>facilitating empowerment of women and girls from poor and marginalised communities.</b></p>
</div>
</div>
</section>

<section id="about" class="content-section text-center ">
 <h1 class="wow bounceInLeft" data-wow-duration="1s">Have a look</h1>
      <div class="container-fluid ">
        <div class="row">
            <div class="container-fluid bg-1 text-center">
                <video width="100%" height="auto" class="col-lg-12 mx-auto" autoplay muted loop id="myVideo">
                    <source src="aditya_section/myvideo.mp4" type="video/mp4">
                    Your browser does not support HTML5 video.
                  </video>
                  
            </div>
          
        </div>
      </div>
    </section>

<section class="needy">

<h1 class="wow bounceInLeft" data-wow-duration="1s">Initiatives</h1>
    <!-- Page Content -->
    <div class="container">
   <!-- Links -->
      <div class="row">
        <div class="col-lg-6 col-sm-6 text-center mb-4">
          <img class="img-responsive center-block wow fadeIn img-circle" src="images/women.jpg" alt="women empowerment">
          <h3>Help Women Empower</h3>
          <h4><a href="women.php">Encourage Women!Help your country grow</a></h4>
        </div>
        <div class="col-lg-6 col-sm-6 text-center mb-4">
          <img class="img-responsive center-block wow fadeIn img-circle" src="images/syria.png" alt="help for syria">
          <h3>Help for Syria</h3>
          <h4><a href="syria.php">They need your help</a></h4>
        </div>
        
      </div>

    </div>
</section>

<section class="achintya">
<h1 class="wow bounceInLeft" data-wow-duration="1s">Gallery Insights</h1>

<div class="row" id="wrapper">
<div class="col-lg-2 col-sm-6">
<div class="thumbnail">
        <a href="images/1.jpg"  data-lightbox="gallery">
          <img src="images/1.jpg" width="100%" class="img-thumbnail img-responsive center-block wow fadeIn" data-wow-duration="5s"/></a>
</div>
</div>
<div class="col-lg-2 col-sm-6">
<div class="thumbnail">
          <a href="images/3.jpg"  data-lightbox="gallery">
          <img src="images/3.jpg" width="100%"  class="img-thumbnail img-responsive center-block wow fadeIn" data-wow-duration="5s"/></a>
</div>
</div>
<div class="col-lg-2 col-sm-6">
<div class="thumbnail">
          <a href="images/5.jpg"  data-lightbox="gallery">
          <img src="images/5.jpg" width="100%" class="img-thumbnail img-responsive center-block wow fadeIn" data-wow-duration="5s"/></a>
</div>
</div>
<div class="col-lg-2 col-sm-6">
<div class="thumbnail">
        <a href="images/7.jpg"  data-lightbox="gallery">
          <img src="images/7.jpg" width="100%" class="img-thumbnail img-responsive center-block wow fadeIn" data-wow-duration="5s"/></a>
</div>
</div>
<div class="col-lg-2 col-sm-6">
<div class="thumbnail">
        <a href="images/2.jpeg"  data-lightbox="gallery">
          <img src="images/2.jpeg" width="100%" class="img-thumbnail img-responsive center-block wow fadeIn" data-wow-duration="5s"/></a>
</div>
</div>
<div class="col-lg-2 col-sm-6">
<div class="thumbnail">
        <a href="images/4.jpg"  data-lightbox="gallery">
          <img src="images/4.jpg" width="100%" class="img-thumbnail img-responsive center-block wow fadeIn" data-wow-duration="5s"/></a>
</div>
<h3 class="pull-right"><a href="gallery.php">See More</a></h4>
</div>
<script src="js/lightbox-plus-jquery.min.js"></script>
</div>

</section>
<section class="maps">
<h1 class="wow bounceInLeft" data-wow-duration="1s">Our Location</h1>
    <div id="map">
    <script>
      function initMap() {
        var uluru = {lat: 12.823105, lng: 80.04528};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 4,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAFwBinpJOkj0Lny4YKBE7OvtKV0giGNJ8&callback=initMap">
    </script>
    </div>
</section>
<section class="contact-form" id="contact">
<h1 class="wow bounceInLeft" data-wow-duration="1s">Contact Us</h1>
<form action="vendor/index.php" method="post" class="query-form">
<label>NAME</label>
<input type="text" id="name" name="name" placeholder="Your good name please" required="yes"><br><br>
<label>EMAIL</label>
<input type="email" id="email" name="email" placeholder="Enter You email" required="yes"><br><br>
<label>SUBJECT</label>
<input text="text" id="subject" name="subject" placeholder="Enter Subject" required="yes"><br><br>
<label>MESSAGE</label>
<textarea type="text" id="msg" name="msg-body" placeholder="Write Your  query here" required="yes"></textarea><br><br>
<input type="submit" name="submit" value="Submit">
<span id="error_message" class="text-danger"></span>  
                     <span id="success_message" class="text-success"></span> 
</form>

</section>

<?php
include('footer.php');
?>

<!--aditya video section part-->

   <!-- Bootstrap core JavaScript -->
 


<script>
	
$(document).ready(function(){
	$(".navbar-toggle").on("click",function(){
		$(this).toggleClass("active");
	})
})

</script>
<script src="js/wow.min.js"></script>
              <script>
              new WOW().init();
              </script>


              

<script src="https://app.engati.com/static/js/chat_widget.js"></script>
<script>EngtChat.init({"bot_key": "96898d35d0a84542", "e":"p", "bot_name":"NGO Bot","welcome_msg":true});</script>
</body>
</html>


